### ISSUE TITLE
The Wonders of Delta Time

### ISSUE THREAD

**Issue by CoderTheTyler** [NotreDameProgrammingClub/ND-programming-group-1#5]
I've noticed something rather interesting: you don't seem to be keeping track of the time elapsed between frames? If you are, let me know, but I couldn't find anything while scrolling through your code. Delta time allows you to maintain accurate performance across a wide variety of performances. If you just do the same thing every frame, there is no way to determine if there are more frames being run per second than on another machine. So, do you have it? :D

**Comment by tac550** [comment]
I was aware of the ability to do this but never added it for some reason. How much do you think I'd need to rewrite to get it working? What does it involve?

**Comment by CoderTheTyler** [comment]
Well not much at all. Just a few more parameters to your update methods and some multiplication and bam! You're good. Would you like me to do some basic work on that?

**Comment by tac550** [comment]
Yes, please. Thanks for the help!
